title: 🔧 Fix glazed command compatibility issues for legacy CLI behavior
description: |
  Fixed critical compatibility issues to ensure glazed commands are safe replacements for legacy CLI:

  1. PPA Parameter Layer compatibility:
     - Added legacy "componentId" parameter alongside "component-id" 
     - Updated PPASettings struct to handle both parameter names
     - Added logic to prioritize legacy value when explicitly set

  2. Discovery defaults alignment:
     - Changed discover parameter default from false to true
     - Matches legacy behavior where discovery was enabled by default

  3. UDP broadcast flag compatibility:
     - Fixed address flag from "-u" to "-a" (legacy compatibility)
     - Fixed port flag from "-P" to "-p" (legacy compatibility)

  4. Parameter layer cleanup for UDP broadcast:
     - Removed irrelevant PPA connection flags from UDP broadcast command
     - Created minimal layer set (UDP broadcast + logging + glazed only)
     - Eliminates confusing/irrelevant flags like --component-id, --discover

  All tests pass and commands build successfully. Legacy CLI users can now safely
  migrate to glazed commands without changing their flag usage patterns.

  APIs added:
  - PPASettings.ComponentIDLegacy field for backward compatibility
  - Legacy componentId parameter definition in PPA layer
  - Minimal layer construction for UDP broadcast commands

  Tests run:
  - go build ./... - PASS
  - CLI help verification - PASS  
  - Parameter flag verification - PASS
