// Code generated by "stringer -type=StatusType"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusCommandClient-258]
	_ = x[StatusRequestClient-262]
	_ = x[StatusResponseClient-257]
	_ = x[StatusErrorClient-265]
	_ = x[StatusWaitClient-321]
	_ = x[StatusCommandServer-2]
	_ = x[StatusRequestServer-6]
	_ = x[StatusResponseServer-1]
	_ = x[StatusErrorServer-9]
	_ = x[StatusWaitServer-65]
}

const (
	_StatusType_name_0 = "StatusResponseServerStatusCommandServer"
	_StatusType_name_1 = "StatusRequestServer"
	_StatusType_name_2 = "StatusErrorServer"
	_StatusType_name_3 = "StatusWaitServer"
	_StatusType_name_4 = "StatusResponseClientStatusCommandClient"
	_StatusType_name_5 = "StatusRequestClient"
	_StatusType_name_6 = "StatusErrorClient"
	_StatusType_name_7 = "StatusWaitClient"
)

var (
	_StatusType_index_0 = [...]uint8{0, 20, 39}
	_StatusType_index_4 = [...]uint8{0, 20, 39}
)

func (i StatusType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _StatusType_name_0[_StatusType_index_0[i]:_StatusType_index_0[i+1]]
	case i == 6:
		return _StatusType_name_1
	case i == 9:
		return _StatusType_name_2
	case i == 65:
		return _StatusType_name_3
	case 257 <= i && i <= 258:
		i -= 257
		return _StatusType_name_4[_StatusType_index_4[i]:_StatusType_index_4[i+1]]
	case i == 262:
		return _StatusType_name_5
	case i == 265:
		return _StatusType_name_6
	case i == 321:
		return _StatusType_name_7
	default:
		return "StatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
